### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by teoseller** [Phoenix1747/fake-sandbox#3]
Is possible to ask to add new process to the actual implemented process? I’m asking to add fiddler related process.  thank you a lot

**Comment by NuclearPhoenixx** [comment]
Of course it's possible! I'm just not asking for custom processes at the installation because of possible input mistakes, if you meant that.

You can go edit the installer file with your favorite text editor and look for this line right at the top:
```
SET @proc='WinDbg.exe','idaq.exe','wireshark.exe','vmacthlp.exe','VBoxService.exe','VBoxTray.exe','procmon.exe','ollydbg.exe','vmware-tray.exe','idag.exe','ImmunityDebugger.exe'
```

Just add any process you'd like to start and you're done :)

**Comment by NuclearPhoenixx** [comment]
Did this answer your question?

**Comment by teoseller** [comment]
Yes thank a lot for the answer and for your job.!
